volumes:
    db_data: {}

services:
    go:
        container_name: tasclock-server
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            DB_TYPE: ${DB_TYPE}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_NAME: ${DB_NAME}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            CLIENT_PORT: ${CLIENT_PORT}
            PORT: ${PORT}
            PRODUCTION_MODE: ${PRODUCTION_MODE}
            SECRET_SALT: ${SECRET_SALT}
            HASH_COUNT: ${HASH_COUNT}
            ACCESS_TOKEN_EXPIRE: ${ACCESS_TOKEN_EXPIRE}
            REFRESH_TOKEN_EXPIRE: ${REFRESH_TOKEN_EXPIRE}
            JWT_SECRET: ${JWT_SECRET}
        ports:
            - ${PORT}:${PORT}
        tty: true
        stop_signal: SIGINT
        volumes:
            - .:/app
    # postgres:
    #     container_name: tasclock-db
    #     image: postgres:13
    #     environment:
    #         POSTGRES_USER: ${DB_USER}
    #         POSTGRES_PASSWORD: ${DB_PASS}
    #         POSTGRES_DB: ${DB_NAME}
    #     ports:
    #         - ${DB_PORT}:${DB_PORT}
    #     volumes:
    #         - db_data:/var/lib/postgresql/data
    mysql:
      container_name: tasclock-db
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASS}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
      ports:
        - ${DB_PORT}:${DB_PORT}
      volumes:
        - db_data:/var/lib/mysql
        - ./db:/docker-entrypoint-initdb.d
